export const commonText = {
  welcomeMessage: "Enter the Studio",
  letstart: "Sign in to access your projects, crew, and daily slates.",
  email: "Email Address",
  enteremailaddress: "Enter your email address",
  password: "Password",
  enterpassword: "Enter your password",
  enterConfirmPassword: "Confirm your password",
  forgotPassword: "Forgot password?",
  newToVirtue: "New To Virtue ?",
  createAccount: "Create Account",
  letsGetStarted: "Let’s get started, buddy !",
  yourJOurneyBegingHere: "Your journey begins here",
  name: "Name",
  enterName: "Enter Name",
  confirmPassword: "Confirm Password",
  letsGo: "Let's Go",
  alreadyHaveAnAccount: "Already have an acount",
  login: "Login",
  almostThere: "Almost there, buddy!",
  codeSentDescription:
    "We’ve sent a 4-digit code to your email. Enter it below to verify your account",
  veiryAndContinue: "Verify & Continue",
  resendOtpIn: "Resend OTP in",
  letsFixThis: "Let’s fix this, buddy",
  dontStress: "Don’t stress. We’ll get you back in within seconds",
  continue: "Continue",
  continueYourJourney: "Continue Your Journey",
  youAreAlmostBack: "You’re almost back, buddy",
  justSetYOurPassword: "Just set your new password below.",
  resetPassword: "Reset Password",
  Update: "Update",
  UpdateProfle: "Update Profile",
  logout: "Logout",
  uploadanimage: "Upload An Image",
  dummyText:
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  profileName: "Premium User",
  profileHandle: "unique_creator",
  profileBio:
    "Creating digital experiences and loving life. 🚀 \nAlways building, always growing. Let's connect!",
  profileLink: "🔗 myuniverse.com/unique",
  posts: "Posts",
  followers: "Followers",
  following: "Following",
  highlights: "Highlights",
  achievementVault: "Achievement Vault",
  reels: "Reels",
  tags: "Tags",
  editProfile: "Edit Profile",
  shareProfile: "Share Profile",
  search: "Search",
  settings: "Settings",
  yourActivity: "Your Activity",
  saved: "Saved",
  archive: "Archive",
  accountPrivacy: "Account Privacy",
  notification: "Notification",
  notifications: "Notifications",
  help: "Help",
  blockedAccounts: "Blocked Accounts",
  bites: "Bites",
  DevicePermissions: "Device Permissions",
  ChangePassword: "Change Password",
  dataUsage: "Data Usage",
  monetization: "Monetization",
  tagsAndMentions: "Tags & Mentions",
  ratings: "Ratings",
  savedPosts: "Saved Posts",
  likes: "Likes",
  reviews: "Reviews & Ratings",
  whatAreYouCreating: "What are you creating?",
  chooseATypeToGetStarted: "Choose a type to get started",
  selectMedia: "Select Media",
  content: "Content",
  outOf10Selected: " / 10 selected",
  oneVideoSelected: "1 video selected",
  selectOneVideo: "Select 1 video",
  next: "Next",
  published: "Published!",
  post: "post",
  yourPostIsLive: "Your post is live. Go share it with the world",
  goToFeed: "Go to Feed",
  viewPost: "View Post",
  cover: "Cover",
  tapToChange: "Tap to change",
  tagPeople: "Tag People",
  searchUserPlaceholder: "Search user by handle or name...",
  tagged: "Tagged",
  addTag: "+ Tag",
  doneTagging: "Done Tagging",
  promotionalPosters: "Promotional Posters & Artwork",
  portraitPoster: "Portrait Poster",
  forFeedDiscovery: "For feed & discovery",
  landscapeBackdrop: "Landscape Backdrop",
  forCinemaBanner: "For cinema banner",
  productionVideoFiles: "Production Video Files",
  officialTrailerTeaser: "Official Trailer Teaser",
  recommendedTrailerLength: "Recommended length: 1 to 3 minutes",
  trailerAttached: "Trailer Attached",
  selectTrailer: "Select Trailer",
  projectTitle: "Project Title",
  projectTitlePlaceholder: "Enter movie or production title...",
  filmTagline: "Film Tagline",
  taglinePlaceholder: "e.g. The rise and battle for supreme control.",
  synopsisAndStoryline: "Synopsis & Storyline",
  synopsisPlaceholder:
    "Tell viewers about your plot, characters, and directorial vision...",
  castAndCrewLabel: "Cast & Crew (Shown on Movie Screen)",
  addActorDirectorCrew: "Add Actor, Director, Creator or Crew",
  selectRoleToAssign: "Select Role to Assign",
  searchCreatorPlaceholder: "Search creator by name or role...",
  added: "Added",
  addAs: "+ Add as ",
  doneAddingCastCrew: "Done Adding Cast & Crew",
  releaseYearAndDuration: "Release Year & Estimated Duration",
  releaseYearPlaceholder: "Release Year (2026)",
  durationPlaceholder: "Duration (2h 15m)",
  videoFormatResolution: "Video Format / Resolution",
  primaryGenre: "Primary Genre",
  contentAgeRating: "Content Age Rating",
  enableTipButton: "Enable Tip Button",
  tipButtonSubtitleMovie: "Allow viewers & fans to send financial appreciation",
  biteCaptionDetails: "Bite Caption & Details",
  biteCaptionPlaceholder: "Write an engaging caption for your short...",
  audioSoundDesign: "Audio & Sound Design",
  originalStudioSound: "Original Studio Sound",
  tapToSelectMusic: "Tap to select music track or mix",
  creatorHashtags: "Creator Hashtags",
  enableComments: "Enable Comments",
  tipButtonSubtitleBite: "Allow fans to tip you directly on this short bite",
  enableCommunityFeedback: "Enable community feedback and discussions",
  studioThoughtUpdate: "Your Studio Thought or Update",
  storyTextPlaceholder:
    "Share production updates, casting news, or thoughts...",
  slateTopicMood: "Slate Topic & Mood",
  studioLocationSet: "Studio Location or Film Set",
  locationTagPlaceholder: "Tag studio stage, cinema, or filming location...",
  details: "Details",
  publishProject: "Publish Project",
  postContent: "Post Content",
  cancel: "Cancel",
  contentOwnershipConfirmation:
    "I accept all the content provided above belongs to me and I am the original owner of all the content.",
  monetizeMasterpieces: "Monetize Your Masterpieces",
  monetizationSubtitle:
    "Earn revenue directly from your films. Apply for the Indiemate Creator Fund.",
  eligibilityChecklist: "Eligibility Checklist",
  reqViews: "Over 10,000 total portfolio views",
  reqOriginal: "100% Original Content",
  applicationForm: "Creator Application Form",
  fullLegalName: "Full Legal Name",
  enterLegalName: "Enter your full legal name",
  countryOfResidence: "Country of Residence",
  enterCountry: "e.g. United States, United Kingdom",
  payoutEmail: "Payout Email Address",
  enterPayoutEmail: "Enter paypal or bank transfer email",
  legalAgreements: "Legal Agreements",
  copyrightAgreement:
    "I confirm that I own 100% of the copyrights (including audio, visuals, and performances) for all content I monetize. I understand that uploading stolen content will result in an immediate ban and forfeiture of earnings.",
  termsAgreement:
    "I agree to the Indiemate Creator Monetization Terms & Conditions and understand I am responsible for my own local taxes.",
  submitApplication: "Submit Application",
  applicationSubmittedTitle: "Application Submitted!",
  applicationSubmittedDesc:
    "Your application to the Indiemate Creator Fund is under review. Our curation team will verify your portfolio and send payout instructions to your email within 48 hours.",
  returnToSettings: "Return to Settings",
  addPrefix: "Add ",
  takePhoto: "Take Photo",
  chooseGallery: "Choose Gallery",
  removeCurrent: "Remove current",
  profileSetup: "Profile setup",
  done: "Done",
  fullNameLabel: "Full Name",
  enterFullName: "Enter your full name",
  usernameLabel: "Username",
  enterUsername: "Enter username",
  bioLabel: "Bio",
  enterBio: "Enter bio",
  emailLabel: "Email",
  enterEmail: "Enter email address",
  appName: "Indiemate",
  appNameCaps: "INDIEMATE",
  from: "from",
  home: "Home",
  register: "Register",
  heroHeadline: "The Digital Screening Room for Independent Cinema.",
  heroSubheadline:
    "Showcase your portfolio in pristine 4K, connect with verified production crews, and apply for the Creator Monetization Fund.",
  ctaApplyMonetization: "Apply for Monetization",
  ctaExplorePortfolios: "Explore Portfolios",
  featurePlayerTitle: "The Native Player",
  featurePlayerDesc:
    "Edge-to-edge playback, lossless audio support, and dynamic aspect ratio locking (16:9 to 2.35:1) to preserve your exact framing.",
  featureCrewTitle: "Verified Crew Sync",
  featureCrewDesc:
    "Tag your entire crew. From the Director of Photography to the Colorist, build an interconnected, verified filmography.",
  featureGearTitle: "Gear & Specs Meta-Data",
  featureGearDesc:
    "Log your exact technical setups directly on your projects, from ARRI Alexa Minis to Cooke Anamorphic lenses.",
  monetizationHeader: "Fund Your Next Masterpiece.",
  monetizationCopy:
    "Indiemate partners with creators. If you own 100% of the copyrights to your original films, apply to the Creator Fund for performance-based payouts directly to your Stripe account.",
  features: "Features",
  screeningRoom: "Screening Room",
  editorialPhotographyNotice: "Cinematic Filmography",
};

export const validationConstants = {
  noInternet: "Please check your internet connection.",
  emailRequired: "Please enter email address.",
  invalidEmail: "Please enter valid email address.",
  passwordRequired: "Please enter password.",
  invalidPasswordLogin: "Please enter valid password.",
  otpRequired: "Please enter OTP.",
  invalidOtp: "Please enter valid OTP.",
  enternewPassword: "Please enter new password.",
  invalidPassword:
    "New password must be at least 8 characters long with uppercase, lowercase, number, special character, and no spaces.",
  enterconfirmPassword: "Please enter confirm password.",
  passwordNotMatch: "New password and confirm password does not match.",
};

export const validationSchema = {
  email: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i,
  password:
    /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/,
};
